#!/bin/bash

USER=$2
DOMAIN=$4
PASSWORD=$3
IP=$1
DOMAIN_CONTROL_NAME=$5


# find domain info
echo "[+] dumping domain info"
rpcclient -U "$DOMAIN/$USER%$PASSWORD" -I $IP $DOMAIN_CONTROL_NAME -c 'querydominfo; quit;' > domain_info.txt

# find all users & save the result in txt file
echo "[+] Dumping users"
rpcclient -U "$DOMAIN/$USER%$PASSWORD" -I $IP $DOMAIN_CONTROL_NAME -c 'enumdomusers; quit;' | awk '{print $1}' | awk -F: '{print $2}' | cut -f 2 -d '[' | cut -f 1 -d ']' > users.txt

# find users RID & save the results in txt file
echo "[+] Duming users rid"
rpcclient -U "$DOMAIN/$USER%$PASSWORD" -I $IP $DOMAIN_CONTROL_NAME -c 'enumdomusers; quit;' | awk '{print $2}' | awk -F: '{print $2}' | cut -f 2 -d '[' | cut -f 1 -d ']' > users_rid.txt

# find groups & save the results in txt file
echo "[+] Dumping groups"
rpcclient -U "$DOMAIN/$USER%$PASSWORD" -I $IP $DOMAIN_CONTROL_NAME -c 'enumdomgroups; quit;' | awk -F[ '{print $2}' | awk -F] '{print $1}' > groups.txt

# find groups RID & save the results in txt file
echo "[+] Dumping groups rid"
rpcclient -U "$DOMAIN/$USER%$PASSWORD" -I $IP $DOMAIN_CONTROL_NAME -c 'enumdomgroups; quit;' | awk -F] '{print $2}' | awk -F: '{print $2}' | cut -f 2 -d '[' > groups_rid.txt

# find domain password policy
echo "[+] Dumping domain password policy"
rpcclient -U "$DOMAIN/$USER%$PASSWORD" -I $IP $DOMAIN_CONTROL_NAME -c 'getdompwinfo; quit;' > domain_password_policy.txt

# dumping all users details (this may take a lot of time depends on user count available on domain)
# this type of recon is important because we can find some private infos posted in public places like Description field.
echo "[+] Start dumping detailed user info's"
for rid in $(cat users_rid.txt); do
    rpcclient -U "$DOMAIN/$USER%$PASSWORD" -I $IP $DOMAIN_CONTROL_NAME -c "queryuser $rid; quit;"
done
